__name__ = "ezdl"
__version__ = "0.1.0"
__author__ = "irfanhakim"
__email__ = "irfanhakim.as@yahoo.com"
__description__ = "Video downloader script for YouTube, Instagram, Tik Tok, and more."
__license__ = ""
__url__ = "https://github.com/irfanhakim/ezdl"
